### ISSUE TITLE
Display not working in third person view

### ISSUE THREAD

**Issue by Nobaiha** [Dukhart/UE4_OpenCV#2]
Hi so I tried to recreate this project but in third person view. I followed all the steps and did everything properly. But for some reason I get this in the display 
![image](https://user-images.githubusercontent.com/77299896/112767093-9a02b800-8fc9-11eb-81f2-5a3a7f2d2f25.png)

Do you know what might be causing this? 
[I only did till part2]

**Comment by Nobaiha** [comment]
I tried it out with a blank project too and get the same display... I also tried opening the project in another laptop, the same issue exists.

**Comment by Dukhart** [comment]
Hey, I'm not sure what you mean by 3rd person view can you send a screenshot of the blueprint/script for the camera, I redownloaded the repo into a new project and built it without any problems. From the picture you sent, it looks like the render target that open cv reads is getting incorrect data this could be caused by a pixel format mismatch, or maybe the third-person camera isn't updating the render target. My best guess is the pixel format from the camera and the render target are different.

**Comment by Nobaiha** [comment]
Hey by third person view I meant third person template in unreal engine, but I also tried the project with blank template and still get the same display. 
You mentioned that maybe is happening because of the pixel format mismatch, do you know how to fix it? If you can help I would be so grateful.

**Comment by gamefa** [comment]
Hi there, I am also facing the same problem and I have fixed it. I opened the render Target and change the size to 1920 x1080, then it worked. You may also change the render Target format if you want.
